# -*- coding: utf-8 -*-
"""IEUK LLoyds Banking Group Engineering Skills Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRzBCp9kdwxpN_H17a0CluSiOLfAop9q
"""

from google.colab import files
uploaded = files.upload()

import re
import pandas as pd

# Regular expression to parse log lines
log_pattern = re.compile(
    r'(?P<ip>\d+\.\d+\.\d+\.\d+)\s+-\s+(?P<user>\S+)\s+-\s+\[(?P<timestamp>[^\]]+)\]\s+'
    r'"(?P<method>\S+)\s(?P<path>\S+)\s(?P<protocol>[^"]+)"\s+'
    r'(?P<status>\d+)\s+(?P<size>\d+)\s+"(?P<referer>[^"]*)"\s+"(?P<agent>[^"]+)"\s+(?P<responsetime>\d+)'
)

# Read the log lines from file
parsed_data = []
with open("sample-log.log", 'r') as file:
    for line in file:
        match = log_pattern.match(line)
        if match:
            data = match.groupdict()
            parsed_data.append({
                "IP Address": data["ip"],
                "User": data["user"],
                "Timestamp": data["timestamp"],
                "Method": data["method"],
                "Path": data["path"],
                "Protocol": data["protocol"],
                "Status": int(data["status"]),
                "Size": int(data["size"]),
                "Referrer": data["referer"],
                "User-Agent": data["agent"],
                "Response Time": int(data["responsetime"]),
            })


# Create a DataFrame (table)
df = pd.DataFrame(parsed_data)
df.head()

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style='darkgrid')
import plotly.graph_objs as go
import plotly.offline as py
from scipy import stats

df.describe()

df.isnull().sum()

df[df.duplicated(keep=False)]

for column in df.columns:
    num_distinct_values = df[column].nunique()
    print(f"Column '{column}' has {num_distinct_values} distinct values.")

cols_to_drop = [col for col in df.columns if df[col].nunique() == 1]
df.drop(columns=cols_to_drop)
display(df.head())

# List of common bot indicators in User-Agent
bot_keywords = ["bot", "crawler", "spider", "curl", "python", "wget", "scrapy", "scanner", "requests"]

# Define function to check if a row looks like bot traffic
def is_bot(row):
    user_agent = str(row["User-Agent"]).lower()
    response_time = row["Response Time"]

    return (
        any(keyword in user_agent for keyword in bot_keywords) or
        response_time < 50
    )

df["Suspicious"] = df.apply(is_bot, axis=1)

df.head()

suspicious_counts = df['Suspicious'].value_counts()

plt.figure(figsize=(6, 4))
sns.barplot(x=suspicious_counts.index, y=suspicious_counts.values, hue=suspicious_counts.index, palette="viridis", legend=False)
plt.title("Distribution of Suspicious and Non-Suspicious Logs")
plt.xlabel("Suspicious")
plt.ylabel("Count")
plt.xticks([0, 1], ['Non-Suspicious', 'Suspicious'])
plt.show()

suspicious_logs = df[df["Suspicious"] == True]
suspicious_logs.head()

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x="Response Time", hue="Suspicious", bins=50, kde=True, palette="Set2", multiple="stack")
plt.title("Distribution of Response Time by Suspicious Traffic")
plt.xlabel("Response Time (ms)")
plt.ylabel("Frequency")
plt.show()

suspicious_logs["Suspicious Time"] = suspicious_logs.apply(lambda row: row["Response Time"] < 50, axis=1)
suspicious_logs["Suspicious Agent"] = suspicious_logs.apply(lambda row: any(keyword in str(row["User-Agent"]).lower() for keyword in bot_keywords), axis=1)

suspicious_ua = suspicious_logs[suspicious_logs["Suspicious Agent"] == True]
display(suspicious_ua.head())

ip_avg_response = df.groupby("IP Address")["Response Time"].mean().sort_values(ascending=True)
ip_avg_response_df = ip_avg_response.reset_index().rename(columns={"Response Time": "Avg Response Time"})
ip_avg_response_df.head(10)

suspicious_ip_counts = suspicious_ua["IP Address"].value_counts().head(20) # Display top 20 IPs
plt.figure(figsize=(12, 6))
sns.barplot(x=suspicious_ip_counts.index, y=suspicious_ip_counts.values, hue=suspicious_ip_counts.index, palette="viridis", legend=False)
plt.title("Count of Suspicious IP Addresses (Based on User Agent)")
plt.xlabel("IP Address")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.show()

print(suspicious_ua["User-Agent"].unique())

suspicious_ip_counts.head(10)

import datetime
suspicious_logs['Parsed Time'] = pd.to_datetime(suspicious_logs['Timestamp'], format="%d/%m/%Y:%H:%M:%S")

suspicious_logs = suspicious_logs.sort_values(by=['IP Address', 'Parsed Time'])
suspicious_logs['Time Since Last'] = suspicious_logs.groupby('IP Address')['Parsed Time'].diff().dt.total_seconds()
suspicious_logs['Fast Request'] = suspicious_logs['Time Since Last'] < 2

suspicious_logs.head()

fast_counts = suspicious_logs[suspicious_logs['Fast Request']].groupby('IP Address').size().reset_index(name='Fast Request Count')
fast_counts.head()

# Get total request count per IP
ip_request_counts = suspicious_logs['IP Address'].value_counts().reset_index()
ip_request_counts.columns = ['IP Address', 'Total Requests']

# Get active time range per IP
ip_time_range = suspicious_logs.groupby('IP Address')['Parsed Time'].agg(['min', 'max'])
ip_time_range['Active Duration (s)'] = (ip_time_range['max'] - ip_time_range['min']).dt.total_seconds()

# Combine and calculate frequency
ip_stats = ip_request_counts.merge(ip_time_range, on='IP Address')
ip_stats['Requests per Minute'] = ip_stats['Total Requests'] / (ip_stats['Active Duration (s)'] / 60)

# Flag IPs with high sustained frequency
ip_stats['Frequent Requester'] = ip_stats['Requests per Minute'] > 1
ip_stats.head(10) 
